name: Build and deploy Node.js app to Azure Web App - guidenet-mvp-azure-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: List build directory contents (Windows)
        if: runner.os == 'Windows'
        run: dir ./client/build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./client/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./client/build
      - name: List downloaded build directory contents
        run: ls -la ./client/build
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6108687225664EC4B6F9C75FF482FA8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B911A8B8BD9647608E1DD431DE3251A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C5F17F8A15D44F23AE470710B5B231B4 }}
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "guidenet-mvp-azure-app"
          slot-name: "Production"
          package: ./client/build
